[[language]]
name = "rust"
config = { imports.granularity.group = "item", checkOnSave.command = "clippy" }

[[language]]
name = "c"
file-types = ["c", "h"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
file-types = ["cpp", "hpp", "tpp"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "    " }
