[[language]]
name = "toml"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "rust"
config = { imports.granularity.group = "item" }

[[language]]
name = "c"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }